name: Update Sitemap and Ping Search Engines

on:
  push:
    paths:
      - 'public/**'
      - 'sitemap_updater.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run sitemap updater
      run: python sitemap_updater.py

    - name: Commit updated sitemap
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add public/sitemap.xml
        git commit -m "Update sitemap.xml from workflow" || echo "No changes"
        git push

    - name: Ping Google and Bing
      run: |
        curl "http://www.google.com/ping?sitemap=https://www.respirework.com/sitemap.xml"
        curl "http://www.bing.com/ping?sitemap=https://www.respirework.com/sitemap.xml"