name: Generate SEO Pages

on:
  workflow_dispatch:  # Allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run the script
        run: python generate_pages.py
