from flask import Flask, render_template, redirect, Response
import os

app = Flask(__name__)

with open("locations.txt") as f:
    LOCATIONS = [line.strip().replace(",", "").replace(" ", "").lower() for line in f.readlines()]

with open("topics.txt") as f:
    TOPICS = [line.strip().replace(",", "").replace(" ", "").lower() for line in f.readlines()]

@app.route("/")
def homepage():
    return "Welcome to RespireWork.com"

@app.route("/pages/<slug>.html")
def seo_page(slug):
    for loc in LOCATIONS:
        for topic in TOPICS:
            if slug == f"{topic}_{loc}":
                title = f"Trending {topic.capitalize()} in {loc.capitalize()}"
                description = f"Explore the latest on {topic} happening now in {loc.capitalize()} at RespireWork."
                return render_template("page.html", title=title, description=description)
    return redirect("https://www.respirework.com")

@app.route("/sitemap.xml")
def sitemap():
    urls = []
    for loc in LOCATIONS:
        for topic in TOPICS:
            slug = f"{topic}_{loc}"
            urls.append(f"https://www.respirework.com/pages/{slug}.html")
    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    for url in urls[:100000000000000]:
        xml += f"  <url><loc>{url}</loc></url>\n"
    xml += '</urlset>'
    return Response(xml, mimetype='application/xml')

if __name__ == "__main__":
    app.run(debug=True, port=5000)
