name: Generate Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"  # every 1 minute

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate Pages
        run: |
          pip install -r requirements.txt
          python generate_pages.py

      - name: Commit Pages
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add public/pages/
          git commit -m "Generated pages"
          git push || echo "No changes to commit"
