name: Generate SEO Pages

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Generate SEO pages
        run: python generate_pages.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pages/ sitemap.xml rss.xml || echo "Nothing to add"
          git commit -m "Auto-generate SEO pages" || echo "Nothing to commit"
          git pull --rebase
          git push

      - name: Ping Google & Bing
        run: |
          curl "http://www.google.com/ping?sitemap=https://www.respirework.com/sitemap.xml" || echo "Google ping failed"
          curl "http://www.bing.com/ping?sitemap=https://www.respirework.com/sitemap.xml" || echo "Bing ping failed"
