name: Generate SEO Pages

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install OpenAI SDK
        run: pip install openai

      - name: Run Generator Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_redirect_pages.py

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add docs/
          git commit -m "Generated SEO pages" || echo "No changes"
          git push
