name: Generate Pages

on:
  schedule:
    - cron: "*/1 * * * *"  # Every minute
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List repo contents (debug)
        run: ls -laR

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Page Generator
        run: python generate_pages.py

      - name: Commit & Push (only if there are changes)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add *.html
          git diff --cached --quiet || (git commit -m "Generated/Updated pages" && git push)
