name: Auto Promo Runner

on:
  schedule:
    - cron: "*/1 * * * *"  # Every minute (GitHub doesn’t allow every second)
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Discord
        run: python3 actions/discord_notify.py
      - name: Run Reddit Draft Generator
        run: python3 actions/reddit_promoter.py
      - name: Run RSS Pinger
        run: python3 rss_ping.py
