name: Rebecca Yarros RSS Updater

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-rebecca-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate rebecca-yarros.xml
      run: python rss_submitter.py  # Make sure this file generates rebecca-yarros.xml

    - name: Commit & push updated RSS feed
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add -A
        git status
        if git diff --cached --quiet; then
          echo "✅ No changes to commit."
        else
          git commit -m "Update rebecca-yarros RSS feed"
          git push
        fi
