name: Auto Reddit Post

on:
  workflow_dispatch:  # manual run
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PRAW
        run: pip install -r requirements.txt

      - name: Post to Reddit
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_USER: ${{ secrets.REDDIT_USER }}
          REDDIT_PASS: ${{ secrets.REDDIT_PASS }}
          REDDIT_AGENT: ${{ secrets.REDDIT_AGENT }}
        run: python post_to_reddit.py
