name: RSS Redirect Generator

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:

jobs:
  generate_redirects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run redirect generator script
        run: python generate_redirects_from_rss.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto update: generated RSS redirect HTML files"
            git push
          else
            echo "No changes to commit"
