name: RSS Merger & Feed Generator

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  generate-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run RSS Feed Generator
      run: python rss_submitter.py

    - name: Commit & Push RSS Updates
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add -A
        git status
        if git diff --cached --quiet; then
          echo "✅ No changes to commit."
        else
          git commit -m "Auto update RSS feeds"
          git push
        fi
