name: RSS Aggregator Auto Submitter

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Generate RSS Feeds
      run: python rss_submitter.py

    - name: Commit & Push updated RSS feeds
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add rss.xml empyrean-series.xml rebecca-yarros.xml
        git status
        git commit -m "Auto update RSS feeds" || echo "No changes to commit"
        git push || echo "Nothing to push"
