name: Update Sitemap and Ping Search Engines

on:
  workflow_dispatch:     # Allow manual trigger
  schedule:
    - cron: "*/1 * * * *"  # Every 1 minute

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run sitemap updater
        run: python scripts/update_sitemap.py

      - name: Ping Google and Bing
        run: |
          curl "http://www.google.com/ping?sitemap=https://www.respirework.com/sitemap.xml"
          curl "http://www.bing.com/ping?sitemap=https://www.respirework.com/sitemap.xml"

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sitemap.xml
          git diff --quiet || git commit -m "Auto-update sitemap.xml"
          git push
